---
title: "blast_all_against_all"
author: "Rebeca de Souza Brinco"
date: "20/05/2022"
output: html_document
---




```{r}
library(rBLAST)
source(here::here("code", "functions.R"))
```

```{r}
library(here)
library(tidyverse)
seq_pr5<- Biostrings::readAAStringSet(
    here("products", "result_files", "pr5_nostopcodon.fa"))
```

# Blast with select TLPs
```{r}
blast_pr5 <- blast_search(query = seq_pr5, db=seq_pr5, BLAST_args = "-evalue 1e-10")
head(blast_pr5)
dim(blast_pr5)
```


# Create matrix
```{r}
matrix1 <- blast_pr5 %>%
  pivot_wider(names_from = SubjectID, values_from = Perc.Ident)

library(dplyr)
matrix2 <- matrix1 %>%
  group_by(QueryID) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  select(-Alignment.Length, -Mismatches, -Gap.Openings, -Q.start, -Q.end, -S.start, -S.end, -E, -Bits)

matrix3 <- matrix2 %>%
  select(-QueryID)
row.names(matrix3) <- c("Glyma.01G165400", "Glyma.01G165600", "Glyma.01G165800", "Glyma.01G217600", "Glyma.01G217700", "Glyma.02G047400", "Glyma.02G220900", "Glyma.02G249500", "Glyma.04G023700", "Glyma.04G034300", "Glyma.04G176200", "Glyma.04G225800", "Glyma.05G169700", "Glyma.05G204600", "Glyma.05G204800", "Glyma.05G245800", "Glyma.06G023900", "Glyma.06G139000", "Glyma.06G189100", "Glyma.07G135100", "Glyma.08G053600", "Glyma.08G128000", "Glyma.08G172700", "Glyma.09G003600", "Glyma.10G060300", "Glyma.10G060800", "Glyma.10G061000", "Glyma.10G061700", "Glyma.10G061800", "Glyma.10G062100", "Glyma.11G025600", "Glyma.11G077700", "Glyma.11G077800", "Glyma.11G106100", "Glyma.11G106200", "Glyma.11G140800", "Glyma.11G220700", "Glyma.12G031000", "Glyma.12G031200", "Glyma.12G064300", "Glyma.12G238900", "Glyma.13G082700", "Glyma.14G077267", "Glyma.14G077333", "Glyma.14G077400", "Glyma.14G163700", "Glyma.14G188400", "Glyma.14G219600", "Glyma.15G254700", "Glyma.15G258400", "Glyma.16G126900", "Glyma.16G127100", "Glyma.17G248300", "Glyma.17G258500", "Glyma.17G258600", "Glyma.19G018400")
```


# Plot heatmap
```{r}
library(tiff)
tiff(filename = "Heatmap.tif", width = 800, height = 800)
heatmap3::heatmap3(matrix3, margins = c(8,8))
dev.off()
```

